### ISSUE TITLE
None type error 

### ISSUE THREAD

**Issue by rohit-talele** [NextGenAIGuy/Speech-To-Text-Project#2]
None type error when we try to run the system as it fails to load the model.

**Comment by NextGenAIGuy** [comment]
First fix the dependency error. By installing packages from requirements.txt file. Model can be downloaded directly or through git clone of whisperx repo as shown in the video.

**Comment by rohit-talele** [comment]
i am able to download the wishperx model its giving error for diarization model
![image](https://github.com/user-attachments/assets/d47030e3-9339-43d6-9762-e885c96beacb)

**Comment by NextGenAIGuy** [comment]
You didn't watch my video. In the error its saying the model is private or gated meaning you need to have access first from huggingface model. And then create api key but dont forget to select repository during token creation. And paste that huggingface face token in .env file. Do one thing in my fashion styling assistant video only watch how to get access of gated repo and create huggingface token.

**Comment by rohit-talele** [comment]
i have provided the hugging face token in .env file its still giving an error

**Comment by NextGenAIGuy** [comment]
I also said you have to get access first than create token. Do as i have written the error will go away automatically.
